### ISSUE TITLE
support for 4.9.140-tegra-32.4.4-20201016123640

### ISSUE THREAD

**Issue by vovacooper** [ArduCAM/Camarray_HAT#2]
Hi, 
Hardware: Jetson xavier NX

I installed the image from nvidia website 
https://developer.nvidia.com/embedded/downloads#?cl=date,-1
Jetson NX Developer Kit SD Card Image  JP 4.4.1

My system:
cat /etc/nv_tegra_release
R32 (release), REVISION: 4.4, GCID: 23942405, BOARD: t186ref, EABI: aarch64, DATE: Fri Oct 16 19:37:08 UTC 2020

uname -a
Linux lulav-desktop 4.9.140-tegra #1 SMP PREEMPT Fri Oct 16 12:25:00 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux

I downloaded your latest driver from git (from two days ago)
https://github.com/ArduCAM/Camarray_HAT/blob/main/Jetson/Nano/IMX477/arducam-nvidia-l4t-kernel_4.9.140-32.4.4-20201106140811_arm64_imx477_stereo.deb

Unfortunately i cant install the driver because of a difference in the tegra versions. 

sudo dpkg -i arducam-nvidia-l4t-kernel_4.9.140-32.4.4-20201106140811_arm64_imx477_stereo.deb 
(Reading database ... 160439 files and directories currently installed.)
Preparing to unpack arducam-nvidia-l4t-kernel_4.9.140-32.4.4-20201106140811_arm64_imx477_stereo.deb ...
Unpacking arducam-nvidia-l4t-kernel (4.9.140-32.4.4-20201106140811) over (4.9.140-32.4.4-20201106140811) ...
ls: cannot access 'extlinux.conf_bak': No such file or directory
ls: cannot access 'Image.bak': No such file or directory
dpkg: dependency problems prevent configuration of arducam-nvidia-l4t-kernel:
 arducam-nvidia-l4t-kernel depends on nvidia-l4t-kernel (= 4.9.140-tegra-32.4.4-20201016124427); however:
  Version of nvidia-l4t-kernel on system is 4.9.140-tegra-32.4.4-20201016123640.

dpkg: error processing package arducam-nvidia-l4t-kernel (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 arducam-nvidia-l4t-kernel

can u make a build for me so that is will work with 4.9.140-tegra-32.4.4-20201016123640?

thanks.

**Comment by vovacooper** [comment]
.

**Comment by rptamin** [comment]
I am also receiving the same issue albeit for a slightly different l4t:


dpkg: dependency problems prevent configuration of arducam-nvidia-l4t-kernel:
 arducam-nvidia-l4t-kernel depends on nvidia-l4t-kernel (= 4.9.140-tegra-32.4.4-20201016124427); however:
  Version of nvidia-l4t-kernel on system is 4.9.140-tegra-32.4.4-20201027211332.

dpkg: error processing package arducam-nvidia-l4t-kernel (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 arducam-nvidia-l4t-kernel

**Comment by vovacooper** [comment]
very frustrating,
i was sure that Arducam will provide us with the correct working drivers before i bought this.

**Comment by rptamin** [comment]
I think you need to sudo apt-get update, and the sudo apt-get upgrade. Can you check if your latest version on NX is 4.9.140-tegra-32.4.4-20201027211332 after update? I am unable to upgrade any past that. The current deb file is linked to 2020-11-06 date which I can't upgrade to using apt. @glddiv how can I upgrade my NX to the version supported by the deb file?

**Comment by vovacooper** [comment]
Hi, thanks for the replay.
after update + upgrade i get this:

sudo dpkg -i arducam-nvidia-l4t-kernel_4.9.140-32.4.4-20201106140811_arm64_imx477_stereo.deb 
Selecting previously unselected package arducam-nvidia-l4t-kernel.
(Reading database ... 161553 files and directories currently installed.)
Preparing to unpack arducam-nvidia-l4t-kernel_4.9.140-32.4.4-20201106140811_arm64_imx477_stereo.deb ...
Unpacking arducam-nvidia-l4t-kernel (4.9.140-32.4.4-20201106140811) ...
dpkg: dependency problems prevent configuration of arducam-nvidia-l4t-kernel:
 arducam-nvidia-l4t-kernel depends on nvidia-l4t-kernel (= 4.9.140-tegra-32.4.4-20201016124427); however:
  Version of nvidia-l4t-kernel on system is 4.9.140-tegra-32.4.4-20201027211332.
dpkg: error processing package arducam-nvidia-l4t-kernel (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 arducam-nvidia-l4t-kernel


so as you can see my version is: 4.9.140-tegra-32.4.4-20201027211332.

if i check all the versions of the kernel available: with "apt show -a nvidia-l4t-kernel"


Package: nvidia-l4t-kernel
Version: 4.9.140-tegra-32.4.4-20201027211332
Priority: standard
Section: kernel
Maintainer: NVIDIA Corporation
Installed-Size: 113 MB
Pre-Depends: nvidia-l4t-core (>> 32.4-0), nvidia-l4t-core (<< 32.5-0)
Homepage: http://developer.nvidia.com/jetson
Download-Size: 29.0 MB
APT-Manual-Installed: yes
APT-Sources: https://repo.download.nvidia.com/jetson/t194 r32.4/main arm64 Packages
Description: NVIDIA Kernel Package

Package: nvidia-l4t-kernel
Version: 4.9.140-tegra-32.4.4-20201016123640
Priority: standard
Section: kernel
Maintainer: NVIDIA Corporation
Installed-Size: 113 MB
Pre-Depends: nvidia-l4t-core (>> 32.4-0), nvidia-l4t-core (<< 32.5-0)
Homepage: http://developer.nvidia.com/jetson
Download-Size: 29.0 MB
APT-Sources: https://repo.download.nvidia.com/jetson/t194 r32.4/main arm64 Packages
Description: NVIDIA Kernel Package

Package: nvidia-l4t-kernel
Version: 4.9.140-tegra-32.4.3-20200924161919
Priority: standard
Section: kernel
Maintainer: NVIDIA Corporation
Installed-Size: 102 MB
Pre-Depends: nvidia-l4t-core (>> 32.4-0), nvidia-l4t-core (<< 32.5-0)
Homepage: http://developer.nvidia.com/jetson
Download-Size: 26.7 MB
APT-Sources: https://repo.download.nvidia.com/jetson/t194 r32.4/main arm64 Packages
Description: NVIDIA Kernel Package

Package: nvidia-l4t-kernel
Version: 4.9.140-tegra-32.4.3-20200625213407
Priority: standard
Section: kernel
Maintainer: NVIDIA Corporation
Installed-Size: 102 MB
Pre-Depends: nvidia-l4t-core (>> 32.4-0), nvidia-l4t-core (<< 32.5-0)
Homepage: http://developer.nvidia.com/jetson
Download-Size: 26.7 MB
APT-Sources: https://repo.download.nvidia.com/jetson/t194 r32.4/main arm64 Packages
Description: NVIDIA Kernel Package

Package: nvidia-l4t-kernel
Version: 4.9.140-tegra-32.4.2-20200428141701
Priority: standard
Section: kernel
Maintainer: NVIDIA Corporation
Installed-Size: 102 MB
Pre-Depends: nvidia-l4t-core (>> 32.4-0), nvidia-l4t-core (<< 32.5-0)
Homepage: http://developer.nvidia.com/jetson
Download-Size: 26.7 MB
APT-Sources: https://repo.download.nvidia.com/jetson/t194 r32.4/main arm64 Packages
Description: NVIDIA Kernel Package

Package: nvidia-l4t-kernel
Version: 4.9.140-tegra-32.4.2-20200408182620
Priority: standard
Section: kernel
Maintainer: NVIDIA Corporation
Installed-Size: 102 MB
Pre-Depends: nvidia-l4t-core (>> 32.4-0), nvidia-l4t-core (<< 32.5-0)
Homepage: http://developer.nvidia.com/jetson
Download-Size: 26.7 MB
APT-Sources: https://repo.download.nvidia.com/jetson/t194 r32.4/main arm64 Packages
Description: NVIDIA Kernel Package

as you can see there is no 4.9.140-tegra-32.4.4-20201016124427 available in the apt-get. 
can u please provide a driver for 4.9.140-tegra-32.4.4-20201027211332

thanks

**Comment by rptamin** [comment]
@ArduCAM @glddiv Can we get a fix for this?

**Comment by vovacooper** [comment]
Hi, just made the module work with Jetson Nano i got an hour ago. 
So in conclusion, the Stereo doesn't support Xavier NX :(

**Comment by rptamin** [comment]
Did you use the same .deb file? Does that mean that they intended it only for the Nano and not the NX?

**Comment by vovacooper** [comment]
yep, i used "arducam-nvidia-l4t-kernel_4.9.140-32.4.4-20201106140811_arm64_imx477_stereo.deb" file, which uses 4.9.140-tegra-32.4.4-20201016124427 kernel which only available with the Jetson Nano. 
I dont know if they intended it for the Xavier or not, but for now they didn't provide us with the drives for Xavier :(
i hope they will soon.

**Comment by vovacooper** [comment]
hi Arducam team? are you there?

**Comment by rptamin** [comment]
I found drivers that work: https://github.com/ArduCAM/MIPI_Camera/releases/tag/v0.0.1-nx
Let me know if these work.

**Comment by vovacooper** [comment]
It did work, but only for a few seconds before the Jetson showed me red screen and didn't respond to anything. 
does it work for you? for all resolutions?

**Comment by rptamin** [comment]
The 13fps at 4K was red screen but 60fps at 1080p was very good quality.

**Comment by vovacooper** [comment]
Ill try that too, but i didn't pay for this cameras to get 1080p, and to be more accurate 2 540p halves of a frame. 
BTY, do you have any idea regarding the Half resolution of the image? 
Can we somehow get the synchronised full resolution from both cameras ? or the best we get is 2 halves of 2 camera?
Its very unclear from the few words they give us as a documentation for this product :(
